# Generated by Django 4.1.13 on 2024-07-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос звонка',
                'verbose_name_plural': 'Запросы звонков',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Полное название объекта')),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='case_headers/', verbose_name='Фото в шапку страницы')),
                ('main_video', models.ImageField(blank=True, null=True, upload_to='case_headers/', verbose_name='Видео в шапку страницы')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес')),
                ('customer', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заказчик')),
                ('performer', models.CharField(blank=True, default='АИК «Реновация»', max_length=150, null=True, verbose_name='Исполнитель')),
                ('architector', models.CharField(blank=True, max_length=300, null=True, verbose_name='Архитектор')),
                ('engeneer', models.CharField(blank=True, max_length=300, null=True, verbose_name='Инженер')),
                ('square', models.CharField(blank=True, max_length=30, null=True, verbose_name='Площадь (только цифры)')),
                ('year', models.CharField(blank=True, max_length=250, null=True, verbose_name='Год')),
                ('realize_text', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Реализации')),
                ('image_r_1', models.ImageField(blank=True, null=True, upload_to='realize/', verbose_name='Реализация | 1')),
                ('image_r_2', models.ImageField(blank=True, null=True, upload_to='realize/', verbose_name='Реализация | 2')),
                ('image_r_3', models.ImageField(blank=True, null=True, upload_to='realize/', verbose_name='Реализация | 3')),
                ('image_r_4', models.ImageField(blank=True, null=True, upload_to='realize/', verbose_name='Реализация | 4')),
                ('image_r_5', models.ImageField(blank=True, null=True, upload_to='realize/', verbose_name='Реализация | 5')),
                ('image_r_6', models.ImageField(blank=True, null=True, upload_to='realize/', verbose_name='Реализация | 6')),
                ('visualization_text', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Визуализации')),
                ('image_v_1', models.ImageField(blank=True, null=True, upload_to='visualization/')),
                ('image_v_2', models.ImageField(blank=True, null=True, upload_to='visualization/')),
                ('image_v_3', models.ImageField(blank=True, null=True, upload_to='visualization/')),
                ('image_v_4', models.ImageField(blank=True, null=True, upload_to='visualization/')),
                ('image_v_5', models.ImageField(blank=True, null=True, upload_to='visualization/')),
                ('image_v_6', models.ImageField(blank=True, null=True, upload_to='visualization/')),
                ('analisys_text', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Градостроительном анализе')),
                ('image_a_1', models.ImageField(blank=True, null=True, upload_to='analisys/')),
                ('image_a_2', models.ImageField(blank=True, null=True, upload_to='analisys/')),
                ('image_a_3', models.ImageField(blank=True, null=True, upload_to='analisys/')),
                ('image_a_4', models.ImageField(blank=True, null=True, upload_to='analisys/')),
                ('image_a_5', models.ImageField(blank=True, null=True, upload_to='analisys/')),
                ('image_a_6', models.ImageField(blank=True, null=True, upload_to='analisys/')),
                ('concept_text', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Концепции')),
                ('image_c_1', models.ImageField(blank=True, null=True, upload_to='concept/')),
                ('image_c_2', models.ImageField(blank=True, null=True, upload_to='concept/')),
                ('image_c_3', models.ImageField(blank=True, null=True, upload_to='concept/')),
                ('image_c_4', models.ImageField(blank=True, null=True, upload_to='concept/')),
                ('image_c_5', models.ImageField(blank=True, null=True, upload_to='concept/')),
                ('image_c_6', models.ImageField(blank=True, null=True, upload_to='concept/')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=60, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category'], name='renew_categ_categor_e49fa2_idx'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='renew.category', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['id', 'address'], name='renew_case_id_7f2ace_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['name'], name='renew_case_name_db22ba_idx'),
        ),
    ]
