# Generated by Django 4.1.13 on 2024-06-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('city', models.CharField(max_length=30, verbose_name='Населенный пункт')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Полное название объекта')),
                ('main_img', models.ImageField(upload_to='case_headers/', verbose_name='Фото в шапку страницы')),
                ('main_video', models.ImageField(upload_to='case_headers/', verbose_name='Видео в шапку страницы')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес')),
                ('customer', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заказчик')),
                ('performer', models.CharField(blank=True, default='АИК «Реновация»', max_length=150, null=True, verbose_name='Исполнитель')),
                ('architector', models.CharField(blank=True, max_length=300, null=True, verbose_name='Архитектор')),
                ('square', models.CharField(blank=True, max_length=30, null=True, verbose_name='Площадь (только цифры)')),
                ('year', models.CharField(blank=True, max_length=250, null=True, verbose_name='Год')),
                ('realize_img', models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь в директорию Реализация')),
                ('realize_text', models.TextField(blank=True, max_length=250, null=True, verbose_name='Текст о Реализации')),
                ('visualization_img', models.TextField(blank=True, max_length=250, null=True, verbose_name='Текст о Визуализации')),
                ('analisys_img', models.TextField(blank=True, max_length=250, null=True, verbose_name='Текст о Градостроительном анализе')),
                ('concept_img', models.TextField(blank=True, max_length=250, null=True, verbose_name='Текст о Концепции')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=60, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category'], name='renew_categ_categor_e49fa2_idx'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='renew.category', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['id', 'address'], name='renew_case_id_7f2ace_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['name'], name='renew_case_name_db22ba_idx'),
        ),
    ]
