# Generated by Django 4.1.13 on 2024-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0003_rename_call_id_callme_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callme',
            options={'ordering': ['-created'], 'verbose_name': 'Запрос звонка', 'verbose_name_plural': 'Запросы звонков'},
        ),
        migrations.AddField(
            model_name='case',
            name='analisys_text',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Градостроительном анализе'),
        ),
        migrations.AddField(
            model_name='case',
            name='concept_text',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Концепции'),
        ),
        migrations.AddField(
            model_name='case',
            name='visualization_text',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Визуализации'),
        ),
        migrations.AlterField(
            model_name='case',
            name='analisys_img',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь в директорию Градостроительный анализ'),
        ),
        migrations.AlterField(
            model_name='case',
            name='concept_img',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь в директорию Концепция'),
        ),
        migrations.AlterField(
            model_name='case',
            name='realize_text',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Текст о Реализации'),
        ),
        migrations.AlterField(
            model_name='case',
            name='visualization_img',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь в директорию Визуализация'),
        ),
    ]
