# Generated by Django 4.1.13 on 2024-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0004_alter_callme_options_case_analisys_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='case_headers/', verbose_name='Фото в шапку страницы'),
        ),
        migrations.AlterField(
            model_name='case',
            name='main_video',
            field=models.ImageField(blank=True, null=True, upload_to='case_headers/', verbose_name='Видео в шапку страницы'),
        ),
    ]
